### ISSUE TITLE
Double Colon Changed On Click / Select Autocompletion

### ISSUE THREAD

**Issue by putude** [cdaguerre/ide-intelephense#1]
I try Intelephense on Atom.
I have an issue when selecting a completion on a static class.
One of the colons is disappeared on select.

![class-test](https://user-images.githubusercontent.com/2032438/113991055-a964e980-9884-11eb-97c8-39f6e3eeb4a2.gif)

Using: Atom 1.55.0 X64
OS: Windows 10 64bit

**Comment by cdaguerre** [comment]
This is due to the following issue in the language-client: https://github.com/atom/atom-languageclient/issues/218, I just released a patch with a temporary workaround.
Thanks for reporting!

**Comment by putude** [comment]
thank you for your reply. 
But sadly, the autocompletion not working after update. 
Hopefully, the issue solved shortly and I can enjoy my premium features.  :)

**Comment by cdaguerre** [comment]
I just released an update to the language client. could you confirm that it fixes the issue?

**Comment by putude** [comment]
Sorry for the late reply. 
Yes, all works for now. thank you for the update.
